import { makeStyles } from "@mui/styles";
import { Theme } from "@mui/material/styles";
// #
const usePageStyles = makeStyles((theme: Theme) => ({
  // component Navigation navLinkLeft
  navContainer: {
    position: "absolute",
    top: "0",
    left: "30px",
    width: "94vw",
    borderBlockEnd: `1px solid ${theme.myColors.colorLinie}`,
    height: "56px",
    display: "flex",
    justifyContent: "start",
    alignItems: "center",
    zIndex: "9999",
  },
  bottomNavContainer: {
    position: "absolute",
    bottom: "0",
    left: "30px",
    width: "94vw",
    borderTop: `1px solid ${theme.myColors.colorLinie}`,
    height: "56px",
    display: "flex",
    justifyContent: "start",
    alignItems: "center",

    background: "#010c15",
    zIndex: 999,
  },

  navBoxItem: {
    height: "100%",
    cursor: "default",
  },
  navLink: {
    fontFamily: "Fira Code",
    fontSize: "1rem",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "normal",
    color: `${theme.myColors.textColorNav} !important`,
    textDecoration: "none !important",
    height: "100%",
    width: "100%",
    display: "flex",
    alignItems: "center",
    transition: "color 0.3s ease-in",
  },
  navContainerThree: {
    height: "100%",
    paddingLeft: "20px",
    marginLeft: "100px",
  },
  navContainerThreeBottom: {
    height: "100%",
    marginLeft: "20px",
  },
  navBoxItemCenter: {
    color: theme.myColors.textColorNav,
    cursor: "pointer",
    height: "100%",
    borderBottom: "2px solid transparent",
    transition: "border-bottom-color 0.3s ease-in, color 0.3s ease-in",
  },
  navLinkLeft: {
    fontFamily: "Fira Code",
    fontSize: "1rem",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "normal",
    color: `${theme.myColors.textColorNav}`,
    textDecoration: "none !important",
    height: "56px",
    width: "100%",
    display: "flex",
    borderLeft: `2px solid ${theme.myColors.colorLinie}`,
    padding: "0 10px",
    alignItems: "center",
    transition: "color 0.3s ease-in",
    "&:hover": {
      color: `${theme.myColors.whiteColor} !important`,
    },
  },
  navBoxCenter: {
    fontFamily: "Fira Code",
    fontSize: "1rem",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "normal",
    color: `${theme.myColors.textColorNav}`,
    textDecoration: "none !important",
    height: "100%",
    width: "100%",
    display: "flex",
    borderLeft: `2px solid ${theme.myColors.colorLinie}`,
    borderRight: `2px solid ${theme.myColors.colorLinie}`,
    padding: "0 10px",
    alignItems: "center",
    transition: "color 0.3s ease-in",
    "&:hover": {
      color: `${theme.myColors.whiteColor} !important`,
    },
  },
  navBoxRight: {
    fontFamily: "Fira Code",
    fontSize: "1rem",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "normal",
    color: `${theme.myColors.textColorNav}`,
    textDecoration: "none !important",
    height: "100%",
    width: "100%",
    display: "flex",
    borderRight: `2px solid ${theme.myColors.colorLinie}`,
    padding: "0 10px",
    alignItems: "center",
    transition: "color 0.3s ease-in",
    "&:hover": {
      color: `${theme.myColors.whiteColor} !important`,
    },
  },
  navBoxContact: {
    color: theme.myColors.textColorNav,
    position: "absolute",
    top: "0",
    right: "0",
    cursor: "pointer",
    width: "200px",
    height: "100%",

    borderLeft: `2px solid ${theme.myColors.colorLinie}`,
    padding: "0 10px",
    transition: "border-bottom-color 0.3s ease-in, color 0.3s ease-in",
    "&:hover": {
      borderBottomColor: theme.myColors.hoverDownLinie,
    },
  },
  navLinkContact: {
    fontFamily: "Fira Code",
    fontSize: "1rem",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "normal",
    color: `${theme.myColors.textColorNav} `,
    textDecoration: "none !important",
    height: "100%",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "color 0.3s ease-in",
    "&:hover": {
      color: `${theme.myColors.whiteColor} !important`,
    },
  },
  navTextLink: {
    position: "relative",
    top: "2px,",
    left: "-5px",
  },
  //GameSnake
  snakeContainer: {
    display: "flex",
    justifyContent: "space-evenly",
    width: "100%",
    padding: "30px 0",
    background:
      "linear-gradient(150deg, rgba(23, 85, 83, 0.70) 1.7%, rgba(67, 217, 173, 0.09) 81.82%)",
    boxShadow: "0px 2px 0px 0px rgba(255, 255, 255, 0.30) inset",
    border: "1px solid #0C1616",
    borderRadius: "8px",
    backdropFilter: "blur(32px)",
    position: "relative",
  },
  snakeBackEffectGreen: {
    position: "absolute",
    top: 170,
    left: 220,
  },
  snakeBackEffectPurple: {
    position: "absolute",
    bottom: 110,
    right: 220,
  },
  snakeScreenLogo: {
    position: "absolute",
    top: "50px",
    left: "67px",
  },
  //KeyBoard Container styled
  snakeBoxSetting: {
    marginTop: "35px",
    width: "181.382px",
    height: "142px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: " 8px",
    background: "rgba(1, 20, 35, 0.19)",
  },
  snakeArrowTextOne: {
    marginBottom: "8px !important",
    fontFamily: "Fira Code !important",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "normal",
    position: "relative",
    left: "-4px",
  },
  snakeArrowTextTwo: {
    marginBottom: "16px !important",
    fontFamily: "Fira Code !important",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "normal",
  },
  snakeArrowContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  snakeUp: {
    width: "50px",
    height: "28px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "black",
    borderRadius: "8px",
    position: "relative",
    top: "-5px",
    zIndex: 4,
  },
  snakeArrowWrap: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
  },
  snakeArrowLeft: {
    width: "50px",
    height: "28px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "black",
    borderRadius: "8px",
    position: "relative",
    left: "-5px",
  },
  snakeArrowDown: {
    width: "50px",
    height: "28px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "black",
    borderRadius: "8px",
    zIndex: 4,
  },
  snakeArrowRight: {
    width: "50px",
    height: "28px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "black",
    borderRadius: "8px",
    position: "relative",
    right: "-5px",
    zIndex: 4,
  },
  snakeFoodLeft: {
    position: "relative",
    left: "30px",
    top: "10px",
    color: "#FFF",
    fontFamily: "Fira Code !important",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "normal",
  },
  snakeContainerFood: {
    width: "120px",
    height: "50px",
    margin: "20px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "5px",
    position: "relative",
    zIndex: "10",
  },
  // component LeftHeader
  leftHeaderContainer: {
    width: 520,
    height: 410,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    position: "relative",
    left: "-40px",
  },
  leftHeaderH3: {
    fontFamily: "Fira Code",
    color: `${theme.myColors.colorGrey} !important`,
    fontSize: "18px !important",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "normal",
  },
  leftHeaderH1: {
    fontFamily: "Fira Code",
    color: `${theme.myColors.colorGrey} !important`,
    fontSize: "62px !important",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  leftHeaderH2: {
    fontFamily: "Fira Code",
    color: `${theme.myColors.colorPurple} !important`,
    fontSize: "32px !important",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "normal",
  },
  leftHeaderP: {
    fontFamily: "Fira Code",
    color: `${theme.myColors.textColorNav} !important`,
    fontSize: "16px !important",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "normal",
  },
  leftHeaderSpanOne: {
    fontFamily: "Fira Code",
    color: `${theme.myColors.colorPurple} !important`,
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "normal",
  },
  leftHeaderSpanTwo: {
    fontFamily: "Fira Code",
    color: theme.myColors.colorLightGreen,
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "normal",
  },
  leftHeaderSpanThree: {
    color: theme.myColors.whiteColor,
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "normal",
  },
  leftHeaderSpanFour: {
    fontFamily: "Fira Code",
    color: theme.myColors.colorLightOrange,
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "normal",
    borderBottom: "1px solid transparent",
    transition: "border-bottom 0.3s ease-in",

    "&:hover": {
      borderBottom: "1px solid #E99287",
    },
  },
}));

export default usePageStyles;
