import { makeStyles } from "@mui/styles";
import { Theme } from "@mui/material/styles";

const usePageStyles = makeStyles((theme: Theme) => ({
  //AboutMe
  aboutHoverBtnEffect: {
    "&:hover": {
      transition: "color 0.3s ease-in",
      color: `${theme.myColors.whiteColor} !important`,
    },
  },
  aboutContainer: {
    width: "100%",
    display: "flex",
  },
  aboutLeftNavContainer: {
    width: "267px",
    marginTop: "56px !important",
    borderRight: `1px solid ${theme.myColors.colorLinie}`,
    height: "95vh",
  },
  aboutLeftWrap: {
    width: "94vw !important",
    background: "transparent !important",
    display: "flex",
    borderBottom: `1px solid ${theme.myColors.colorLinie}`,
    left: "30px",
    color: `${theme.myColors.whiteColor} !important`,
    fontFamily: "Fira Code",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 400,
  },
  aboutTextRight: {
    color: theme.myColors.textColorNav,
    position: "relative",
    left: "150px",
    fontFamily: "Fira Code",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 400,
  },
  aboutBtnStyle: {
    color: `${theme.myColors.textColorNav} !important`,
    "&:hover": {
      color: `${theme.myColors.whiteColor} !important`,
    },
  },
  aboutIconBio: {
    color: `${theme.myColors.colorLightOrange} !important`,
  },
  aboutIconInterest: {
    color: `${theme.myColors.colorLightGreen} !important`,
  },
  aboutIconEducation: {
    color: `${theme.myColors.colorPurpleFolder} !important`,
  },
  aboutBtnText: {
    fontFamily: "Fira Code",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
    position: "relative",
    top: "1px",
    left: "-20px",
  },
  aboutBtnEducationStyle: {
    position: "relative",
    left: "15px",
    "&:hover": {
      transition: "color 0.3s ease-in",
      color: `${theme.myColors.whiteColor} !important`,
    },
  },
  aboutBtnEducationFont: {
    fontFamily: "Fira Code",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
    paddingLeft: "10px",
  },
  aboutContactContainer: {
    marginTop: "100px !important",
    fontFamily: "Fira Code",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
    width: "240px",
    position: "relative",
    left: "27px",
    borderTop: `1px solid ${theme.myColors.colorLinie} !important`,
    borderBottom: `1px solid ${theme.myColors.colorLinie} !important`,
    "&:hover": {
      transition: "color 0.3s ease-in",
      color: `${theme.myColors.whiteColor} !important`,
    },
  },
  // next about
  aboutNextContainer: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
  },
  aboutNextWrap: {
    marginTop: "150px",
    color: "white",
    padding: 2,
    borderLeft: "1px solid black",
    height: "80vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "start",
  },
  aboutNextMiniWrap: {
    borderRadius: "15px",
    border: `1px solid ${theme.myColors.colorLinie}`,
    background: theme.myColors.colorDarkBlue,
    padding: "7px 12.5px",
    position: "relative",
    left: "25px",
  },
  aboutNextImgContainer: {
    position: "relative",
    top: "50px",
    borderRadius: "15px",
    border: `1px solid ${theme.myColors.colorLinie}`,
    background: theme.myColors.colorDarkBlue,
    padding: "15px 20px",
    display: "flex",
    flexDirection: "column",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  // TemplateAbout
  tempAboutText: {
    color: theme.myColors.textColorNav,
    fontFamily: "Fira Code",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 450,
    position: "relative",
    top: "150px",
    left: "-25px",
    margin: "0 10px",
    width: "100%",
    height: "90vh",
    display: "flex",
    alignItems: "start",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 2,
  },
  tempAboutNumber: {
    position: "relative",
    left: "-10px",
  },

  // LeftContact
  leftContactLink: {
    textDecoration: "none",
    color: theme.myColors.textColorNav,
  },
  leftContactBtn: {
    position: "relative",
    left: "25px",
  },
  leftContactIcon: {
    marginRight: "10px",
  },

  //Project
  projectContainer: {
    width: "100%",
    display: "flex",
  },
  projectList: {
    width: "267px",
    marginTop: "56px !important",
    borderRight: `1px solid ${theme.myColors.colorLinie}`,
    height: "95vh",
  },
  projectLeftNav: {
    width: "94vw",
    background: "transparent !important",
    display: "flex",
    borderBottom: `1px solid ${theme.myColors.colorLinie} `,
    position: "relative",
    left: "30px",
    color: `1px solid ${theme.myColors.colorLinie} !important`,
    fontFamily: "Fira Code",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 400,
  },
  projectRightText: {
    color: theme.myColors.textColorNav,
    position: "relative",
    left: "174px",
  },
  projectRightForm: {
    marginLeft: "60px",
  },
  projectLabel: {
    color: theme.myColors.textColorNav,
  },
  projectCheckBox: {
    "& svg": { color: theme.myColors.textColorNav },
  },
  projectHoverBox: {
    "&:hover": {
      color: theme.myColors.whiteColor,
      transition: "color 0.3s ease-in",
    },
  },
  projectCategory: {
    marginRight: "15px",
    position: "relative",
    top: "2px",
    left: "5px",
  },
  //SkillSection
  skillContainer: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
  },
  skillWrap: {
    position: "relative",
    top: "150px",
    left: "0px",
    height: "90vh",
    width: "100%",
    maxWidth: "1450px",
    display: "flex",
    justifyContent: "center",
    overflowY: "auto",
  },
  skillPositionWrap: {
    width: "100%",
    padding: "0 10px",
  },
  skillCard: {
    borderRadius: "15px",
    border: `1px solid ${theme.myColors.colorLinie} `,
    background: theme.myColors.colorDarkBlue,
    maxWidth: "470px",
    height: "350px",
    overflow: "hidden",
  },
  skillCardImg: {
    width: "100%",
    height: "200px",
    objectFit: "cover",
  },
  skillCardHeading: {
    padding: "10px",
  },
  skillCardText: {
    fontSize: "1em",
  },
  skillCardContainer: {
    position: "absolute",
    right: "15px",
    top: "25px",
    display: "flex",
    justifyContent: "center",
    gap: "10px",
    background: theme.myColors.colorDarkBlack,
    padding: "5px 10px",
    borderRadius: "10px",
  },
  skillCardIconWrap: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  skillCardBtn: {
    background: `${theme.myColors.colorLinie} !important`,
    "&:hover": {
      background: theme.myColors.colorLinie,
    },
  },
  skillCardLink: {
    color: theme.myColors.whiteColor,
    textDecoration: "none",
    position: "relative",
    top: "2px",
  },

  //ContactMe
  contactContainer: {
    width: "100%",
    display: "flex",
  },
  contactList: {
    width: "267px",
    marginTop: "56px !important",
    borderRight: `1px solid ${theme.myColors.colorLinie} !important`,
    height: "95vh",
  },
  contactLeftWrap: {
    width: "94vw ",
    background: "transparent !important",
    display: "flex",
    borderBottom: `1px solid ${theme.myColors.colorLinie} !important`,
    color: `${theme.myColors.whiteColor} !important`,
    fontFamily: "Fira Code",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 400,
  },
  contactRighttext: {
    color: theme.myColors.textColorNav,
    position: "relative",
    left: "184px",
    fontFamily: "Fira Code",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 400,
  },
  contactBoxNoavigation: {
    color: theme.myColors.textColorNav,
    marginTop: "50px !important",
    fontFamily: "Fira Code",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
    width: "240px",
    position: "relative",
    left: "27px",
    borderTop: `1px solid ${theme.myColors.colorLinie} !important`,
    borderBottom: `1px solid ${theme.myColors.colorLinie} !important`,
    "&:hover": {
      transition: "color 0.3s ease-in",
      color: `${theme.myColors.whiteColor} !important`,
    },
  },
  //contactForm
  contactFormContainer: {
    position: "relative",
    top: "150px",
    margin: "0 10px",
    width: "100%",
    height: "90vh",
    display: "flex",
    alignItems: "start",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 2,
  },
  contactFormWrap: {
    width: "100%",
    maxWidth: "500px",
  },
  contactFormBtn: {
    width: "50%",
    height: "40px",
    marginTop: 2,
    color: theme.myColors.whiteColor,
    textAlign: "right",
    fontFamily: "Fira Code",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "normal",
    borderRadius: "8px",
    background: `${theme.myColors.colorDarkGrey} !important`,
    textTransform: "lowercase",
    "&:hover": {
      background: `${theme.myColors.colorDarkGrey} !important`,
    },
  },
  contactFormBoxText: {
    maxWidth: "600px",
    color: "white",
    padding: 2,
    height: "100vh",
    borderLeft: "1px solid black",
  },

  // Form Styles
  formTextOrange: {
    color: theme.myColors.hoverDownLinie,
    fontFamily: "Fira Code",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "150%",
  },
  formTextPurple: {
    color: theme.myColors.colorPurpleText,
    fontFamily: "Fira Code",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "150%",
  },
  formTextPink: {
    color: theme.myColors.colorPinkText,
    fontFamily: "Fira Code",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "150%",
  },
  formTextGrey: {
    color: theme.myColors.textColorNav,
    fontFamily: "Fira Code",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 450,
    lineHeight: "150%",
  },
}));

export default usePageStyles;
